[package]
name = "drochess"
version = "0.1.0"
edition = "2021"


[dependencies]
lazy_static = "1.5.0"
rand = "0.9.1"
rayon = "1.10.0"
thiserror = "2.0.12"

[profile.release]
opt-level = 3
debug = false
lto = true
codegen-units = 1
panic = "abort"

